domain   = 'kube'

nodes = [
  { :hostname => 'master',  :ip => '10.0.0.10' },
  { :hostname => 'node1',   :ip => '10.0.0.11' },
  { :hostname => 'node2',   :ip => '10.0.0.12' },
  { :hostname => 'node3',   :ip => '10.0.0.13' },
]

memory = 2000

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "centos/7"
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", type: "dhcp"
      nodeconfig.vm.network :private_network, ip: node[:ip], virtualbox__intnet: domain
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.name = node[:hostname]+"."+domain
        vb.memory = memory
        vb.cpus = 1
      end
      nodeconfig.vm.provision "file", source: "hosts", destination: "hosts"
      nodeconfig.vm.provision "shell", inline: "yum update -y && yum upgrade -y"
      nodeconfig.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "id_rsa"
      nodeconfig.vm.provision "shell", inline: "mv hosts /etc/hosts ; mv id_rsa /home/centos/.ssh/id_rsa"
      #nodeconfig.vm.provision "shell", inline: "useradd centos ; usermod -a -G vagrant centos ; echo SELINUX=disabled >/etc/sysconfig/selinux"
      #nodeconfig.vm.provision "shell", inline: "cp -Rvf /home/vagrant/.ssh/ /home/centos/"
      #nodeconfig.vm.provision "shell", inline: "chown -Rvf centos /home/centos/"
      #nodeconfig.vm.provision "shell", inline: "/usr/sbin/reboot"
    end
  end
end
